server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://dpg-d8470ofaqgkc73adpk6g-a.oregon-postgres.render.com:5432/radha_ai
    username: radha_ai_user
    password: vKfXPbeFasUD1PwLSmwQDAPTpka0kTX1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: siddushiva2699@gmail.com
    password: upzw endy nhuu htag

    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  ai:
    anthropic:
      api-key: DISABLED
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-mini
          max-tokens: 4096
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: ${QDRANT_PORT}
        api-key: ${QDRANT_API_KEY}
        collection-name: askoxy_live
        use-tls: true





management:
  health:
    redis:
      enabled: false

logging:
  level:
    com.askoxy.radhaai: INFO


radha:
  email:
    from: siddushiva2699@gmail.com
    to: bsudheesh123@gmail.com
  n8n:
    enabled: true
    webhook-base-url: http://localhost:5678/webhook-test

gemini:
  api:
    key: AIzaSyCtOA1KiqxAGhb71srDoLz5KBp97fHuTeI