package com.askoxy.radhaai.entity;

import com.askoxy.radhaai.enums.ContentStatus;
import jakarta.persistence.*;
import lombok.*;

/**
 * VideoContent — stores one video upload lifecycle.
 *
 * Status flow:
 *   PENDING  → Radha sees generated content, picks action
 *   APPROVED → added to AI clone (Qdrant) and/or DB
 *   PUBLISHED→ posted to social / blog
 *   REJECTED → discarded
 *   FAILED   → pipeline error
 *
 * Analysis pipeline (3 steps):
 *   audioTranscript → verbatim speech extracted from video audio
 *   visualContent   → on-screen text/slides/graphics extracted from video frames
 *   reasoningNotes  → how both sources were combined by the AI
 *   reasonedContent → final synthesised best content from both sources
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "video_contents")
public class VideoContent extends BaseEntity {

    /** Unique ID returned to frontend for all follow-up calls. */
    @Column(nullable = false, unique = true)
    private String videoId;

    /** Original filename uploaded by Radha. */
    @Column
    private String originalFileName;

    /** Where the video is stored on disk / S3 path. */
    @Column(columnDefinition = "TEXT")
    private String storagePath;

    /** File size in bytes. */
    @Column
    private Long fileSizeBytes;

    // ── Analysis Pipeline Fields ───────────────────────────────────────────

    /**
     * STEP 1 — Verbatim transcript of everything spoken in the video.
     * Extracted by Gemini with an audio-only focused prompt.
     */
    @Column(columnDefinition = "TEXT")
    private String audioTranscript;

    /**
     * STEP 2 — All text, slides, captions, graphics visible on screen.
     * Extracted by Gemini with a visual-only focused prompt.
     */
    @Column(columnDefinition = "TEXT")
    private String visualContent;

    /**
     * STEP 3 — How the AI combined audio + visual sources.
     * Short 1-2 sentence reasoning note for transparency.
     */
    @Column(columnDefinition = "TEXT")
    private String reasoningNotes;

    /**
     * STEP 3 — The FINAL synthesised content (200-300 words).
     * Generated by reasoning over BOTH audioTranscript + visualContent.
     * This is the primary source for approvedContent.
     */
    @Column(columnDefinition = "TEXT")
    private String reasonedContent;

    /**
     * Full Gemini reasoning response (JSON string) — kept for reference/debugging.
     */


    /**
     * Final content that Radha approved (may be edited by hand).
     * Defaults to reasonedContent on submit.
     */
    @Column(columnDefinition = "TEXT")
    private String approvedContent;

    // ── Structured content fields ─────────────────────────────────────────

    @Column(columnDefinition = "TEXT")
    private String title;

    @Column(columnDefinition = "TEXT")
    private String summary;

    @Column(columnDefinition = "TEXT")
    private String intro;

    @Column(columnDefinition = "TEXT")
    private String body;

    @Column(columnDefinition = "TEXT")
    private String closing;

    /** Current pipeline status */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ContentStatus status;

    // ── Social ─────────────────────────────────────────────────────────────

    /**
     * JSON:
     * {
     *   "LINKEDIN": {...},
     *   "INSTAGRAM": {...}
     * }
     */
    @Column(columnDefinition = "TEXT")
    private String socialFormats;

    /**
     * JSON:
     * {
     *   "LINKEDIN": "SUCCESS",
     *   "INSTAGRAM": "FAILED"
     * }
     */
    @Column(columnDefinition = "TEXT")
    private String socialPostResults;

    // ── Blog ───────────────────────────────────────────────────────────────

    @Column(columnDefinition = "TEXT")
    private String blogFormat;

    @Column
    private String blogPostId;

    // ── Clone ──────────────────────────────────────────────────────────────

    @Column
    private String vectorStoreId;

    @Builder.Default
    @Column
    private Boolean addedToClone = false;

    // ── Workflow ───────────────────────────────────────────────────────────

    @Column(columnDefinition = "TEXT")
    private String adminNote;

    @Column
    private String n8nExecutionId;

    @Column
    private String thumbnailUrl;

    /**
     * VIDEO / REEL / SHORT / AUDIO
     */
    @Column
    private String mediaType;

    @Builder.Default
    @Column
    private Boolean blogPublished = false;

    @Builder.Default
    @Column
    private Boolean socialPosted = false;
}